# Workflow name
name: 'Chromatic Deployment'
on: push

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout node
        uses: actions/setup-node@v2
        with:
          node-version: '16.15.0'
      - uses: actions/checkout@v1
      - run: yarn
        #👇 Adds Chromatic as a step in the workflow
      - uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/ to obtain it
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      - name: Install
          run: |
            npm ci
            npm run 
            npm run build:storybook
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@3.6.2
          with:
            branch: gh-pages
            folder: storybook-static