name: Build and Deploy
on:
  push:
    branches:
      - feature/*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout node
        uses: actions/setup-node@v2
        with:
          node-version: '16.15.0'

      - name: Install
        run: |
          npm ci
          npm run 
          npm run build:storybook

      - name: Deploy
        uses: rangle/radius-github-pages
        with:
          folder: storybook-static
          branch: main
